### ISSUE TITLE
Truncate request_bodies at 10 MB

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#13]
The row limit seems to be 10 MB, not 2 MB per this error message: `Row size is larger than: 10485760`

If that's the case, we can raise the ceiling on request (response?) bodies rows.

**Comment by igrigorik** [comment]
If that's true.. that'd be great!

**Comment by rviscomi** [comment]
Seems too good to be true. The pipeline was failing when configured to 10 MB. Reverting back to 2 MB.
