### ISSUE TITLE
Total page size status: 0 bytes

### ISSUE THREAD

**Issue by ebidel** [HTTPArchive/bigquery#15]
Lots of pages reporting 0bytes since April:

<img width="657" alt="screen shot 2017-06-27 at 5 39 12 pm" src="https://user-images.githubusercontent.com/238208/27615797-aa472400-5b5f-11e7-89ed-b80f8444cff2.png">

**Comment by rviscomi** [comment]
Yeah there's a very clear shift on 5/1.

```sql
SELECT
  COUNT(0) AS volume,
  NTH(501, QUANTILES(respSize , 1001)) AS medianSize,
  resp_content_type
FROM
  [httparchive:runs.2017_04_15_requests]
WHERE
  firstHtml = TRUE
GROUP BY
  resp_content_type
ORDER BY
  volume DESC
```

4/15:

Row | volume | medianSize | resp_content_type 
-- | -- | -- | -- 
1 | 199635 | 15308 | text/html; charset=UTF-8   
2 | 123665 | 15213 | text/html; charset=utf-8 
3 | 101477 | 9071 | text/html 

5/1:

Row | volume | medianSize | resp_content_type 
-- | -- | -- | -- 
1 | 192466 | 0 | text/html; charset=UTF-8 
2 | 119705 | 2327 | text/html; charset=utf-8 
3 | 98493 | 688 | text/html


I'll take an AI to investigate.

cc @pmeenan as this correlates with the Linux agent switch.

**Comment by rviscomi** [comment]
Maybe be a side-effect of the Content-Length bug @pmeenan found today.

**Comment by max-ostapenko** [comment]
@pmeenan is there anything we can fix using available crawl data during backfill?

**Comment by pmeenan** [comment]
You might be able to see if any of the other bytes columns has usable data, but given it's from ~7 years ago, I'm not sure it's worth bothering.

**Comment by max-ostapenko** [comment]
Ok, then closing.
