### ISSUE TITLE
Discrepancy in totals

### ISSUE THREAD

**Issue by max-ostapenko** [HTTPArchive/bigquery#198]
Calculating pages and requests totals with JOIN and without gives different results:
- 723 pages
- 68463 requests

1. Without JOIN:
```sql
SELECT
  COUNT(DISTINCT page) total_pages,
  COUNT(0) total_requests
FROM
  `httparchive.all.requests`
WHERE
  date = "2024-06-01"
  AND client = "desktop"
  AND is_root_page
```

Result:
total_pages | total_requests
-- | --
12740316 | 1312177986

2. With JOIN:
```sql
SELECT
  COUNT(DISTINCT pages.page) total_pages,
  COUNT(0) total_requests
FROM
  `httparchive.all.pages` pages
INNER JOIN
  `httparchive.all.requests`requests
ON
  pages.page = requests.page
WHERE
  pages.date = "2024-06-01"
  AND requests.date = "2024-06-01"
  AND pages.client = "desktop"
  AND requests.client = "desktop"
  AND pages.is_root_page
  AND requests.is_root_page
```

Result:
total_pages | total_requests 
-- | --
12739593 | 1312109523

Checking the discrepancies between the 2 tables returns no rows:
```sql
SELECT DISTINCT
  pages.page,
  requests.page
FROM `httparchive.all.pages` AS pages
FULL OUTER JOIN `httparchive.all.requests` AS requests
ON pages.page = requests.page
WHERE
  pages.date = "2024-06-01"
  AND requests.date = "2024-06-01"
  AND pages.client = "desktop"
  AND requests.client = "desktop"
  AND pages.is_root_page
  AND requests.is_root_page
  AND (pages.page IS NULL OR requests.page IS NULL)
```

**Comment by tunetheweb** [comment]
Your last `FULL OUTER JOIN` is incorrect as once you set `WHERE` clauses you filter out NULLs. Unfortunately you HAVE to set a `date` `WHERE` clause on this table :-(

So the way to do this is like this:

```sql
WITH pages AS (
  SELECT DISTINCT
    page
  FROM
    `httparchive.all.pages`
  WHERE
    date = "2024-06-01"
    AND client = "desktop"
    AND is_root_page
),
requests AS (
  SELECT DISTINCT
    page
  FROM
    `httparchive.all.requests`
  WHERE
    date = "2024-06-01"
    AND client = "desktop"
    AND is_root_page
)

SELECT DISTINCT
  pages.page,
  requests.page
FROM
  pages
FULL OUTER JOIN
  requests
ON
  pages.page = requests.page
WHERE
  (pages.page IS NULL OR requests.page IS NULL)
```

This shows there are some missing page rows on both sides.

This is somewhat expected as we have a 10MB limit on uploads per row so may not be able to upload the page data (which consists of large payload, large Lighthouse payload, and large custom metrics, plus all the other fields) but requests or vide versa.

Maybe we should clear down the request rows for missing pages and vice versa? Or try the page upload first (as that's the one most likely to fail) and cancel the request uploads if that fails? But with both of those we lose visibility as to how big an issue this is.

723 pages out of 12.7 million pages is an acceptable loss to me. We always get issues with processing so much data (and with the wild and wacky web pages people put out there!) so there's always going to be some level of data that cannot be processed.

**Comment by max-ostapenko** [comment]
Thanks.
Yeah, the discrepancy is OK.
It's rather I wasn't sure if it's related to the new tables format (checking data in 2018 was giving exact same results) or my SQL.

I agree that making the discrepancy visible is the "best practice".
That was actually my goal - to check that none of the top sites are impacted.

```sql
WITH pages AS (
  SELECT DISTINCT page
  FROM `httparchive.all.pages`
  WHERE date = "2024-05-01"
    AND client = "desktop"
    AND is_root_page
),
requests AS (
  SELECT DISTINCT page
  FROM `httparchive.all.requests`
  WHERE date = "2024-05-01"
    AND client = "desktop"
    AND is_root_page
    AND is_main_document
), urls AS (
  SELECT DISTINCT
    CONCAT(origin,'/') as crux_origin,
    experimental.popularity.rank AS rank
  FROM `chrome-ux-report.all.202405`
)

SELECT DISTINCT *
FROM (
  SELECT DISTINCT
    pages.page AS pages_origin,
    requests.page AS requests_origin
  FROM pages
  FULL OUTER JOIN requests
  ON (pages.page = requests.page)
  WHERE pages.page IS NULL
    OR requests.page IS NULL
) AS discrep
LEFT JOIN urls
ON urls.crux_origin = discrep.pages_origin
  OR urls.crux_origin = discrep.requests_origin
ORDER BY rank ASC NULLS LAST
```

Most of the top ranked origins indeed have issues when loading the webpage.
