### ISSUE TITLE
Add field comparable to firstHtml to the har.request tables

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#21]
The runs.request tables include a `firstHtml` field to indicate that the request is for the parent document.

Queries on the har.request tables must join on the corresponding runs table to get this info. There are tens of millions of requests in each table, so the join is expensive.

To simplify queries and make them less expensive, add a boolean field comparable to `firstHtml` to the har.request tables. It should share the same logic as the runs table; first 200 response with HTML mime type.

**Comment by igrigorik** [comment]
Would this be a step in the Dataflow pipeline?

**Comment by rviscomi** [comment]
Yes, it should be annotated during the iteration over the requests in the HAR file: https://github.com/HTTPArchive/bigquery/blob/0489d8e96a7b733e475af5eebfd937f92a20c2f1/dataflow/java/src/main/java/com/httparchive/dataflow/BigQueryImport.java#L252

This field would also be valuable on the har.bodies tables.

**Comment by max-ostapenko** [comment]
Closing as there is currently `is_main_document` column in `all.requests` table.
