### ISSUE TITLE
Views for "Latest Requests" on Desktop and Mobile Are Returning Page Data Instead of Requests

### ISSUE THREAD

**Issue by paulcalvano** [HTTPArchive/bigquery#28]
The VIEWs for `httparchive:latest.requests_desktop` and `httparchive:latest.requests_mobile` seem to be querying the `summary_pages` tables instead of the `summary_requests` tables.

<img width="478" alt="screen shot 2018-03-21 at 8 11 01 am" src="https://user-images.githubusercontent.com/7459458/37709107-7e7410f2-2cdf-11e8-9c70-04491f7ec761.png">

**Comment by rviscomi** [comment]
Thanks! Bad copy pasta. Fixed now.
