### ISSUE TITLE
HAR dataset does not have Alexa ranking data

### ISSUE THREAD

**Issue by igrigorik** [HTTPArchive/bigquery#3]
`runs.*` tables [have a `rank` attribute](https://discuss.httparchive.org/t/archive-of-alexa-ranks/188) for each page, whereas `har.*` files produces by WPT do not. 

@souders where and how do we populate the ranking data? It'd be nice to have this within our HAR files.

**Comment by stevesouders** [comment]
We do that in the HTTP Archive crawl code. We know that from the Alexa Top 1M download.

**Comment by igrigorik** [comment]
Ah, found it: http://s3.amazonaws.com/alexa-static/top-1m.csv.zip

Steve, whereabouts in the pipeline? Is there merit in exposing this in the HAR's generated by WPT? Or, do we want to add this later? /cc @pmeenan

**Comment by stevesouders** [comment]
It's saved with each result to the pages table - in batch_lib.inc.

**Comment by igrigorik** [comment]
Hmm, I see. I guess we have two approaches for BigQuery:

1. We can import the alexa rankings as a separate table [rank, domain], against which you could join..
2. We can do the join at import time and write it out into the pages table.

The latter is probably the better route.. I'd just need to figure out how to hook that up as part of the pipeline.
