### ISSUE TITLE
CommandException: Invalid command "application/json".

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#34]
During `generateReports.sh` at the end of each metric being generated, I noticed the following error:

`CommandException: Invalid command "application/json".`

Ensure that the JSON files are being uploaded to GCS correctly.

**Comment by rviscomi** [comment]
Here's the code in the context of the error:

```sh
# Run the query on BigQuery.
result=$(cat $query \
	| $BQ_CMD)
# Make sure the query succeeded.
if [ $? -eq 0 ]; then
	# Upload the response to Google Storage.
	echo $result \
		| gsutil  -h "Content-Type: application/json" cp - $gs_url
else		
```

Maybe a newer version of gsutil doesn't like the `-h` flag?

**Comment by rviscomi** [comment]
Found the problem. It doesn't like the space after `Content-Type:`. Not sure how this ever worked 😕

**Comment by igrigorik** [comment]
> It doesn't like the space after Content-Type:

That's silly. Looks like they "fixed" (broke) this in some recent release.
