### ISSUE TITLE
BigQuery import is paused due to a DataFlow SDK issue

### ISSUE THREAD

**Issue by RByers** [HTTPArchive/bigquery#4]
@igrigorik [said](https://github.com/HTTPArchive/httparchive/issues/66#issuecomment-214969224):

> @RByers there was a regression in latest DataFlow SDK so I paused the automated imports... I can work around it though if its high priority.

We're beginning to rely on this data more and more in blink API owner discussions (eg. this particular came up in the context of [this intent to remove](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/remove$20url$20service$20worker/blink-dev/HuA7Ng9U0oc/CYvfMoeyBwAJ).  So having the data flowing regularly is definitely valuable.  In many cases the Feb data is good enough though, so I can't really say it's that urgent (yet).

**Comment by igrigorik** [comment]
I'll investigate this today/tomorrow. Stay tuned.

**Comment by igrigorik** [comment]
@RByers should be fixed now!

![image](https://cloud.githubusercontent.com/assets/10652/15059024/d7ac3824-12d4-11e6-88f8-75cba677bb72.png)

- I've addressed a few bugs in the pipeline that were causing import failures
- I've reimported all the runs from Jan 1 - April 15th, for both Chrome and Android
- I've modified the table names to get chronological ordering in the web UI
- I've split "bodies" into a separate table from "responses": this makes running queries against responses _much_ cheaper and faster; you can join against the bodies table if you want both, or only scan the body content without forcing a JSON parse. 

For latest and greatest, see: https://bigquery.cloud.google.com/dataset/httparchive:har

Last but not least.. Automated imports should be back online now.

**Comment by RByers** [comment]
Awesome, thanks a ton!
