### ISSUE TITLE
Incomplete page resources in httparchive.response_bodies.* tables

### ISSUE THREAD

**Issue by tomayac** [HTTPArchive/bigquery#46]
The site [Wired](https://www.wired.com/) registers a service worker located at https://www.wired.com/sw.js and references a web app manifest located at https://www.wired.com/manifest.json. While the service worker is available in several runs, the manifest is not: 

```sql
SELECT
  *
FROM
  `httparchive.response_bodies.*`
WHERE
  url = "https://www.wired.com/manifest.json"
  OR url = "https://www.wired.com/sw.js"
```

Web app manifests are generally indexed, as can be seen in this quick test:

```sql
SELECT
  url,
  body
FROM
  `httparchive.response_bodies.*`
WHERE
  url LIKE "%/manifest.json"
  AND body LIKE "%\"short_name\":%"
LIMIT
  10
```

I am not sure what causes the manifest to not be included, but I think Wired's manifest should be indexed as well, the HTML referencing it definitely was indexed:

```sql
SELECT
  page,
  url,
  body
FROM
  `httparchive.response_bodies.*`
WHERE
  page = "http://www.wired.com/"
  AND (url = "http://www.wired.com/"
    OR url = "https://www.wired.com/")
  AND body LIKE "%manifest.json%"
```

(CC: @rviscomi and @jeffposnick)

**Comment by jeffposnick** [comment]
I'm not sure if it's relevant to how HTTP Archive indexing works, but I've previously observed that `manifest.json` is fetched outside the context of the actual page—which is to say, the request for the web app manifest bypasses the service worker's fetch handler. (Requests for the favicon are similar in that regard.)

**Comment by rviscomi** [comment]
@pmeenan seems like something related to WPT. Can you investigate?

**Comment by tomayac** [comment]
I did a quick test on WebPageTest, and FWIW `manifest.json` is there: https://www.webpagetest.org/result/180719_E5_77fc740619949cbb945edf01e3103575/1/details/#step1_request497

**Comment by pmeenan** [comment]
That was on an actual phone.  Running on a desktop browser with emulation it [doesn't load](https://www.webpagetest.org/result/180719_1K_5d1b85632632f76f9a05ce8728f910d3/1/details/#waterfall_view_step1).  I am pretty sure it's actually a Chrome emulation bug for the mobile emulation.  We can't run actual devices at HA scale so it's unlikely to get fixed unless the underlying issue in Chrome is fixed (worth opening a crbug if there isn't one already).

**Comment by tomayac** [comment]
> worth opening a crbug if there isn't one already

Cool, will check and open a bug if need be.

**Comment by tomayac** [comment]
https://crbug.com/865461.

**Comment by tomayac** [comment]
Migrated to https://github.com/WPO-Foundation/wptagent/issues/168. Closing here.
