### ISSUE TITLE
Deduplicate generate_report.sh and generate_reports.sh

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#49]
The only difference between the scripts is that _reports iterates through the histograms/timeseries directories and queries each SQL file.

Rewrite _reports so it simply calls _report for each metric, passing through all of the flags. This way all of the query/lens/storage logic is in one script.

**Comment by tunetheweb** [comment]
Do we need `generate_report.sh` anymore with the enhancements in #100 to be able to run reports matching a glob using the `-r` option:

```
sql/generate_reports.sh -tfh 2021_06_01 -r "crux*"
```

That's how I tend to run single reports since it also allows running a subset of reports rather than running one by one.
