### ISSUE TITLE
Pages table have two entries for each URL

### ISSUE THREAD

**Issue by gunesacar** [HTTPArchive/bigquery#5]
The `httparchive:runs.2016_09_15_pages` table seems to have two entries for each page:
```
SELECT rank, url FROM [httparchive:runs.2016_09_15_pages] 
WHERE rank > 0
ORDER BY rank ASC
LIMIT 10
>>
1 	1	http://www.google.com/ 	 
2 	1	http://www.google.com/ 	 
3 	2	http://www.youtube.com/ 	 
4 	2	http://www.youtube.com/ 	 
5 	3	http://www.facebook.com/ 	 
6 	3	http://www.facebook.com/ 	 
7 	4	http://www.baidu.com/ 	 
8 	4	http://www.baidu.com/ 	 
9 	5	http://www.yahoo.com/ 	 
10 	5	http://www.yahoo.com/

SELECT count(rank) FROM [httparchive:runs.2016_09_15_pages] 
>> 980874
SELECT count(DISTINCT rank) FROM [httparchive:runs.2016_09_15_pages] 
>> 471366

```
If this is intentional, would be nice to note in http://httparchive.org/about.php#testchanges 
PS: Apologies if this is not the right place to file the issue.

**Comment by igrigorik** [comment]
Thanks for reporting this! Looks like our import ran multiple times (hmmm... looking into). 

New (fixed) tables should are being imported as I write this.
