### ISSUE TITLE
httparchive.latest.summary_requests_desktop/mobile not updated

### ISSUE THREAD

**Issue by foolip** [HTTPArchive/bigquery#76]
`summary_pages_desktop` was updated on July 1, but the `summary_requests_mobile` table hasn't been updated since May 1:

![image](https://user-images.githubusercontent.com/498917/61628729-6a8f9a00-ac83-11e9-8214-c41be5d6850c.png)
![image](https://user-images.githubusercontent.com/498917/61628707-5d72ab00-ac83-11e9-8a4b-66af06d09813.png)

As a result of this, it's not possible to use the two tables together by joining on `pageid`. I'm instead having to use `JSON_EXTRACT(payload, '$._contentType') AS contentType` on the full requests table.

Context: I'm updating the [HTTP Archive for web compat decision making](https://docs.google.com/document/d/1cpjWFoXBiuFYI4zb9I7wHs7uYZ0ntbOgLwH-mgqXdEM/edit?usp=sharing) doc.

**Comment by rviscomi** [comment]
The most recent runs of the scheduled queries for desktop/mobile summary requests have failed with this error:

> Job 226352634162:scheduled_query_5d1b264f-0000-22bc-a112-f4f5e80d17d0 (table summary_requests_mobile) failed with error **INVALID_ARGUMENT: Cannot read field '_gzip_save' of type STRING as INT64**; JobID: 226352634162:scheduled_query_5d1b264f-0000-22bc-a112-f4f5e80d17d0

`_gzip_save` is type STRING in 2019_06_01_desktop, so the wildcard query is failing. I'll convert that field to INTEGER and rerun the scheduled queries.

**Comment by rviscomi** [comment]
A few other tables have this type mismatch due to https://github.com/HTTPArchive/httparchive.org/issues/135 so it will be a bit more work to get the scheduled query running.

Instead I'll update the Dataflow pipeline to handle the copying of the latest tables.

**Comment by foolip** [comment]
Thanks @rviscomi! Looking forward to the July data :)

**Comment by rviscomi** [comment]
Latest summary_requests should be generated properly thanks to https://github.com/HTTPArchive/httparchive.org/issues/203.

I'll create a new issue to track handling latest table creation from the Dataflow pipeline.
