### ISSUE TITLE
Prune Lighthouse audits from LHR

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/bigquery#83]
Per https://github.com/GoogleChrome/lighthouse/pull/10716#issuecomment-648520092 we should prune the `full-page-screenshot` and `final-screenshot` audits.

**Comment by max-ostapenko** [comment]
@rviscomi is it still relevant?

**Comment by tunetheweb** [comment]
I believe @pmeenan did his a while ago. You can see the latest here:

https://github.com/search?q=repo%3AHTTPArchive%2Fwptagent+keep_lighthouse_screenshots+OR+lighthouseScreenshots&type=code

and here:

https://github.com/HTTPArchive/wptagent/blob/a7ca702add1ceeee19586a5833b0740e32420294/HTTPArchive/httparchive.py#L264-L267
