### ISSUE TITLE
Lighthouse `2021_01_01_mobile` table missing

### ISSUE THREAD

**Issue by connorjclark** [HTTPArchive/bigquery#94]
![image](https://user-images.githubusercontent.com/4071474/106805665-9b001480-662c-11eb-95ca-7ee231e1b7dd.png)

There's a desktop table, but no mobile ...

**Comment by bazzadp** [comment]
Think you were looking at the `pages` table in above screenshot not Lighthouse?

Either way @paulcalvano sorted both, but still looking at `summary_requests` table which had some issues last month.
